#! /bin/bash
VERSION="3.7.2"
IMAGE=nrdk-$VERSION.dmg

test -f $IMAGE && rm $IMAGE
./scripts/create-dmg --window-size 553 300 \
                     --background background.png \
                     --icon-size 140 \
                     --volname "NRDK - $VERSION" \
                     --icon "Applications" 420 180 \
                     --icon "server" 140 180 \
                     $IMAGE \
                     data/
