#! /bin/bash
VERSION=$1
IMAGE=nrdk-$VERSION.dmg

rm -rf data/
mkdir data

cp -r ../../archive/$VERSION/* data/
cp -r $OPENCV_DIR/../../../build/ data/
chmod +x BowlerStudio
cp BowlerStudio data/
 
 
test -f $IMAGE && rm $IMAGE
./scripts/create-dmg --window-size 553 300 \
                     --background background.png \
                     --icon-size 140 \
                     --volname "NRDK - $VERSION" \
                     --icon "Applications" 420 180 \
                     --icon "server" 140 180 \
                     $IMAGE \
                     data/
